# HCDE 530 — Week 5: First Look at a Dataset
### A standard sequence of operations for any dataset you encounter

Open this notebook in Cursor. Run each cell with **Shift + Enter**. Read the output before moving to the next cell — the output is the point.

---

**The first-look checklist** — run these in order on any new dataset:

| Step | Operation | Question it answers |
|------|-----------|---------------------|
| 1 | `df.head()` / `df.tail()` | What does the data look like? |
| 2 | `df.info()` | What are the columns and types? |
| 3 | `df.describe()` | What are the numbers doing? |
| 4 | `df.isnull().sum()` | What's missing? |
| 5 | `df['col'].value_counts()` | What are the most common values? |
| 6 | `df[df['col'] condition]` | What does a filtered subset look like? |
| 7 | `df.groupby('col')['num'].mean()` | How do groups compare? |

---

## Setup

Run this cell first. It imports pandas and confirms your version.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print("pandas version:", pd.__version__)

pandas version: 3.0.2

---
## Step 1 — Load the data and take a first look

`pd.read_csv()` loads a CSV file into a DataFrame. `df.head()` shows the first five rows. This is always your first move.

### What is a DataFrame?

A **DataFrame** is pandas' main way of storing tabular data. You can think of it like a spreadsheet or a CSV loaded into Python: it has rows, columns, and column names.

Pandas uses DataFrames because they make it easier to inspect, filter, summarize, clean, and analyze data with short commands. Instead of manually looping through every row in a CSV file, you can ask questions like:

```python
df.head()
df['rating'].mean()
df[df['rating'] < 3]
```

In this notebook, `df` is the name of our DataFrame. Once the CSV is loaded into `df`, every later step uses that DataFrame to explore the dataset.

In [2]:
df = pd.read_csv('app_reviews_demo.csv')
df.head()

,id,app,category,rating,review,date,helpful_votes,verified_purchase,device_type,app_version
0,1,Fieldkit,field research,1,Auto-transcription accuracy on accented speake...,2023-03-31,37,True,mobile,2.5.0
1,2,Fieldkit,field research,2,Search results are slow when the repository is...,2024-07-28,12,True,mobile,2.5.3
2,3,Lookback,user research,4,One-click export to Notion is a feature I use ...,2024-03-08,21,True,desktop,5.2.0
3,4,Dovetail,research repository,5,My whole team can comment on the same session ...,2023-12-19,38,True,NaN,2.0.0
4,5,Fieldkit,field research,5,Works offline and syncs when I get back to WiF...,2024-01-23,5,True,desktop,2.5.3

`df.tail()` shows the last five rows — useful for spotting truncated exports or checking whether the file ended cleanly.

In [3]:
df.tail()

,id,app,category,rating,review,date,helpful_votes,verified_purchase,device_type,app_version
495,496,Dovetail,research repository,5,Bulk-tagging across sessions is a huge time sa...,2023-10-02,46,True,desktop,1.8.4
496,497,Maze,usability testing,3,The fundamentals are strong; the extras feel h...,2024-02-14,29,True,desktop,4.2.3
497,498,Miro,collaborative whiteboard,5,Video clips export cleanly with timecodes intact.,2023-06-20,7,True,tablet,9.3.0
498,499,Fieldkit,field research,5,Custom fields on participants let me filter by...,2024-08-05,43,True,mobile,3.0.0
499,500,Lookback,user research,4,The guest access feature is perfect for extern...,2024-05-09,31,True,mobile,5.1.2

---
## Step 2 — Check the structure — `df.info()`

`df.info()` tells you:
- How many rows and columns you have
- The data type of each column (`int64`, `object`, `bool`, `float64`)
- How many **non-null** values are in each column

Look at the non-null count column carefully. Any column with fewer non-null values than total rows has missing data.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 500 non-null    int64
 1   app                500 non-null    str
 2   category           500 non-null    str
 3   rating             500 non-null    int64
 4   review             500 non-null    str
 5   date               500 non-null    str
 6   helpful_votes      500 non-null    int64
 7   verified_purchase  500 non-null    bool
 8   device_type        437 non-null    str
 9   app_version        389 non-null    str
dtypes: bool(1), int64(3), str(6)
memory usage: 35.8 KB

---
## Step 3 — Summarize the numbers — `df.describe()`

`df.describe()` gives you count, mean, min, max, and quartiles for every numeric column. Useful for spotting:
- Unexpected min or max values (outliers)
- Whether a column's range makes sense
- Whether the mean and median (50%) are far apart (skew)

In [5]:
df.describe()

               id      rating  helpful_votes
count  500.000000  500.000000     500.000000
mean   250.500000    3.946000      23.464000
std    144.481833    1.184013      13.766471
min      1.000000    1.000000       0.000000
25%    125.750000    3.000000      11.000000
50%    250.500000    4.000000      23.500000
75%    375.250000    5.000000      35.000000
max    500.000000    5.000000      47.000000

`describe()` skips non-numeric columns by default. Pass the `include='all'` parameter to see categorical columns too (count, unique, top, freq).

In [6]:
df.describe(include='all')

,id,app,category,rating,review,date,helpful_votes,verified_purchase,device_type,app_version
count,500.000000,500,500,500.000000,500,500,500.000000,500,437,389
unique,NaN,5,5,NaN,227,350,NaN,2,3,18
top,NaN,Miro,collaborative whiteboard,NaN,Real-time co-editing on affinity diagrams is s...,2023-08-08,NaN,True,mobile,5.2.0
freq,NaN,121,121,NaN,12,4,NaN,368,210,35
mean,250.500000,NaN,NaN,3.946000,NaN,NaN,23.464000,NaN,NaN,NaN
std,144.481833,NaN,NaN,1.184013,NaN,NaN,13.766471,NaN,NaN,NaN
min,1.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN
25%,125.750000,NaN,NaN,3.000000,NaN,NaN,11.000000,NaN,NaN,NaN
50%,250.500000,NaN,NaN,4.000000,NaN,NaN,23.500000,NaN,NaN,NaN
75%,375.250000,NaN,NaN,5.000000,NaN,NaN,35.000000,NaN,NaN,NaN
max,500.000000,NaN,NaN,5.000000,NaN,NaN,47.000000,NaN,NaN,NaN

---
## Step 4 — Find the missing values — `df.isnull().sum()`

`df.isnull()` returns a DataFrame of True/False — True wherever a value is missing. `.sum()` counts the Trues per column.

In plain English you might ask the agent: 
>“For each column in the DataFrame, count how many cells are empty or missing.”

**Why this matters before any analysis:** if you want to group things, you might run a `groupby()` on a column that has nulls. Pandas silently drops those rows. You may not notice — but your results will be wrong.

In [7]:
df.isnull().sum()

id                     0
app                    0
category               0
rating                 0
review                 0
date                   0
helpful_votes          0
verified_purchase      0
device_type           63
app_version          111
dtype: int64

### Track rows with missing `device_type`

Every row where `device_type` is null is copied into a separate table called `null_device_type`. That leaves the main `df` unchanged and gives you an explicit audit list of those reviews (IDs, apps, ratings, etc.) for follow-up or export.

In [8]:
null_device_type = df.loc[df["device_type"].isna()].copy().reset_index(drop=True)
print("rows with missing device_type:", len(null_device_type))
null_device_type

rows with missing device_type: 63

,id,app,category,rating,review,date,helpful_votes,verified_purchase,device_type,app_version
0,4,Dovetail,research repository,5,My whole team can comment on the same session ...,2023-12-19,38,True,NaN,2.0.0
1,6,Lookback,user research,5,The guest access feature is perfect for extern...,2024-11-08,14,False,NaN,5.3.1
2,8,Maze,usability testing,5,I was running my first study within 20 minutes...,2023-06-25,34,False,NaN,4.1.0
3,10,Miro,collaborative whiteboard,3,"Works fine — nothing remarkable, nothing broken.",2024-08-03,45,True,NaN,9.4.0
4,19,Lookback,user research,5,Automatic session indexing makes it easy to fi...,2024-06-29,8,True,NaN,5.3.1
...,...,...,...,...,...,...,...,...,...,...
58,461,Dovetail,research repository,5,Custom fields on participants let me filter by...,2024-10-24,14,True,NaN,1.8.4
59,474,Maze,usability testing,4,GPS tagging for field observations is exactly ...,2023-05-01,30,True,NaN,4.0.1
60,475,Lookback,user research,5,Works offline and syncs when I get back to WiF...,2023-07-19,32,True,NaN,5.1.2
61,485,Dovetail,research repository,5,I can tag clips without leaving the playback v...,2024-08-26,32,True,NaN,1.9.0
62,491,Maze,usability testing,5,Bulk-tagging across sessions is a huge time sa...,2023-10-30,10,True,NaN,4.0.1

### New table — rows that are **not** missing `device_type`

The main `df` still includes every row. This table keeps **only** reviews where `device_type` has a value (rows with NaN in that column are dropped). Use it when you want to analyze or export just reviews with a known device, separate from `null_device_type` and from the full `df`.

The variable below is called `df_not_missing_device_type`. Equivalent filter: `df[df["device_type"].notna()]`.

In [9]:
df_not_missing_device_type = df.dropna(subset=["device_type"]).copy().reset_index(drop=True)
print("full df rows:", len(df), "| not missing device_type:", len(df_not_missing_device_type))
df_not_missing_device_type.head()

full df rows: 500 | not missing device_type: 437

,id,app,category,rating,review,date,helpful_votes,verified_purchase,device_type,app_version
0,1,Fieldkit,field research,1,Auto-transcription accuracy on accented speake...,2023-03-31,37,True,mobile,2.5.0
1,2,Fieldkit,field research,2,Search results are slow when the repository is...,2024-07-28,12,True,mobile,2.5.3
2,3,Lookback,user research,4,One-click export to Notion is a feature I use ...,2024-03-08,21,True,desktop,5.2.0
3,5,Fieldkit,field research,5,Works offline and syncs when I get back to WiF...,2024-01-23,5,True,desktop,2.5.3
4,7,Fieldkit,field research,5,Project folders keep multi-phase studies manag...,2023-06-16,23,True,mobile,3.0.0

### Statistical test: is **rating** different when `device_type` is missing?

Comparing means is a start. To ask whether a gap is plausibly due to **chance**, we run hypothesis tests. **Ratings are ordinal (1–5)**, so treat the Mann–Whitney result as the primary read; Welch’s *t*-test assumes ratings behave like continuous numbers (common but stronger). The **chi-square** test asks whether the **whole rating distribution** (1s, 2s, …) differs between rows with vs without a device label—not only the average.

**How to read *p*-values:** if *p* is small (often below 0.05), you would rarely see a gap this large if the two groups were truly identical—that supports a **statistically significant** difference. It does **not** prove why the gap exists (confounding is possible). Always report **sample sizes** and **descriptive stats** next to *p*.

The next cell uses **only** `pandas`, `numpy`, and the standard-library `statistics` module (no SciPy), so it should run in any environment where your Week 5 notebook already runs.

In [15]:
import numpy as np
from scipy import stats

rating_missing = df.loc[df["device_type"].isna(), "rating"]
rating_known = df.loc[df["device_type"].notna(), "rating"]

n_m, n_k = len(rating_missing), len(rating_known)
print("Sample sizes")
print("  missing device_type:", n_m)
print("  known device_type:  ", n_k)
print()
print("Rating — descriptive")
print("  missing:  mean", round(rating_missing.mean(), 3), "  median", rating_missing.median(), "  std", round(rating_missing.std(), 3))
print("  known:    mean", round(rating_known.mean(), 3), "  median", rating_known.median(), "  std", round(rating_known.std(), 3))
print("  difference in means (missing − known):", round(rating_missing.mean() - rating_known.mean(), 3))
print()

# Ordinal-friendly: same distribution of ranks? (two-sided)
u_stat, p_mannwhitney = stats.mannwhitneyu(
    rating_missing, rating_known, alternative="two-sided"
)
print("Mann–Whitney U (non-parametric, good for 1–5 ratings)")
print("  U =", round(u_stat, 2), "   p-value =", round(p_mannwhitney, 5))
print()

# Parametric comparison (treats stars as numeric)
t_stat, p_welch = stats.ttest_ind(rating_missing, rating_known, equal_var=False)
print("Welch’s t-test (numeric shortcut; use with caution on Likert data)")
print("  t =", round(t_stat, 3), "   p-value =", round(p_welch, 5))
print()

pooled_sd = np.sqrt(
    ((n_m - 1) * rating_missing.var(ddof=1) + (n_k - 1) * rating_known.var(ddof=1))
    / (n_m + n_k - 2)
)
cohen_d = (rating_missing.mean() - rating_known.mean()) / pooled_sd
print("Effect size — Cohen’s d (missing − known, pooled SD):", round(cohen_d, 3))
print("  (rough guides: small ~0.2, medium ~0.5, large ~0.8)")
print()

# Full distribution: missing vs not × rating categories
ct = pd.crosstab(df["device_type"].isna(), df["rating"], rownames=["missing_device_type"])
chi2, p_chi, dof, _ = stats.chi2_contingency(ct)
print("Chi-square test (does the rating *distribution* differ?)")
print("  χ² =", round(chi2, 3), "   df =", dof, "   p-value =", round(p_chi, 5))
print()
print("Counts: rows = missing device_type?, columns = rating")
print(ct)
print()

alpha = 0.05
print(f"Conclusion at α = {alpha} (typical teaching threshold)")
for label, p in [
    ("Mann–Whitney", p_mannwhitney),
    ("Welch t", p_welch),
    ("Chi-square", p_chi),
]:
    verdict = "reject H₀ — difference is statistically significant" if p < alpha else "do not reject H₀ — not significant at this α"
    print(f"  {label}: p = {p:.5f} → {verdict}")

ModuleNotFoundError: No module named 'scipy'

### So what? 
Good question. Finding missing values is only the first step. The “so what?” is: missing data can change your results, especially when you group or summarize.

If `device_type` has 63 missing values (which we now know it does!), you have a few reasonable choices:

1. **Keep them as their own category**
   
     Plain English for the agent: 
     >“Treat missing device types as `Unknown` so they still show up in the analysis.” This is often the best first move because it makes the missingness visible.

```python
     df['device_type'] = df['device_type'].fillna('Unknown')
     df.groupby('device_type')['rating'].mean()
```

2. **Drop rows with missing values**
   
     Plain English for the agent: 
     >“Only analyze rows where `device_type` is known.” This is okay if the missing rows are small in number and not important to the question. But here, 63 out of 500 is about 13%, so dropping them could affect the result.

```python
     df_clean = df.dropna(subset=['device_type'])
     df_clean.groupby('device_type')['rating'].mean()
```

3. **Ask whether the missingness matters**
   
     Before deciding, compare the missing rows to the non-missing rows. Plain English:
     > “Do reviews with missing device type have different ratings than reviews with known device type?”

```python
     df[df['device_type'].isnull()]['rating'].mean()
     df[df['device_type'].notnull()]['rating'].mean()
```
If they look different, dropping them may bias your analysis.

### A good rule of thumb:

_If the missing column is important to your question, don’t silently drop it. Either keep missing values as `Unknown`, or explain why you removed them._

---
## Step 5 — Distribution of a column — `value_counts()`

`value_counts()` counts how many times each unique value appears. It's the most useful single operation for categorical data.

Use it to answer: *What are the most common values? Is the data balanced or skewed toward one category?*

In [ ]:
# How many reviews per app?
df['app'].value_counts()

In [ ]:
df['device_type'].value_counts(dropna=False)

### What's the distribution of ratings?

In [ ]:
df['rating'].value_counts().sort_index()

---
## Step 6 — Filter to a subset — boolean indexing

`df[condition]` returns only the rows where the condition is True. The condition is written as a comparison inside the brackets.

This is the same as Excel's filter — but repeatable, stackable, and documented in your code.

Ask the agent:
>“Using pandas, show me only the reviews where rating is less than 2. Use df[condition] syntax and explain what the filtered DataFrame contains.”

In [11]:
# Reviews with a rating of 2 or below
low_rated = df[df['rating'] <= 2]

print(f"{len(low_rated):,} low-rated reviews ({len(low_rated)/len(df):.1%} of total)")
low_rated.head()

72 low-rated reviews (14.4% of total)

,id,app,category,rating,review,date,helpful_votes,verified_purchase,device_type,app_version
0,1,Fieldkit,field research,1,Auto-transcription accuracy on accented speake...,2023-03-31,37,True,mobile,2.5.0
1,2,Fieldkit,field research,2,Search results are slow when the repository is...,2024-07-28,12,True,mobile,2.5.3
26,27,Fieldkit,field research,2,No built-in way to generate a structured debri...,2024-04-04,8,True,mobile,2.5.0
31,32,Maze,usability testing,1,Session sharing links occasionally expire befo...,2024-06-27,10,True,tablet,4.2.3
32,33,Lookback,user research,2,Loading large projects takes noticeably longer...,2024-11-22,15,True,desktop,5.2.0

You can stack two conditions with & (and) or | (or). Parentheses are required around each condition.

In [ ]:
df[(df['rating'] <= 2) & (df['app'] == 'Fieldkit')].head(10)

---
## Step 7 — Compare across groups — `groupby()`

`groupby()` splits the DataFrame by a categorical column, then applies an aggregation function (mean, count, sum, etc.) to a numeric column within each group.

This answers the sprint question: *How does [metric] vary by [category]?*

In [12]:
# Average rating per app — sorted lowest to highest
df.groupby('app')['rating'].mean().round(2).sort_values()

app
Fieldkit    3.67
Lookback    3.90
Maze        4.00
Miro        4.02
Dovetail    4.12
Name: rating, dtype: float64

In [13]:
# More than one stat at once with .agg()
df.groupby('app')['rating'].agg(['mean', 'count', 'std']).round(2)

          mean  count   std
app
Dovetail  4.12     89  1.03
Fieldkit  3.67     92  1.29
Lookback  3.90    105  1.18
Maze      4.00     93  1.16
Miro      4.02    121  1.20

In [14]:
# Groupby across two columns
df.groupby(['app', 'device_type'])['rating'].mean().round(2)

app       device_type
Dovetail  desktop        3.75
          mobile         4.11
          tablet         4.47
Fieldkit  desktop        3.42
          mobile         3.94
          tablet         3.47
Lookback  desktop        3.68
          mobile         3.98
          tablet         3.77
Maze      desktop        3.96
          mobile         3.94
          tablet         3.93
Miro      desktop        3.83
          mobile         4.00
          tablet         4.55
Name: rating, dtype: float64

---
## CourtListener bridge — the five in-class operations on legal-search data

This section uses the **same five operations** from class (`head` / `info`, `value_counts`, boolean filter, `groupby` + `mean`, `isnull`) on a small **CourtListener-shaped** CSV (`courtlistener_firstlook_sample.csv`). It mirrors what you build in `week5_courtlistener_cases.ipynb` when you stack API pulls into `df_mp1` — here you can practice offline without a token.

In [ ]:
from IPython.display import display

# --- Five class operations on CourtListener-shaped rows (see week5_courtlistener_cases.ipynb for live API) ---
cl = pd.read_csv('courtlistener_firstlook_sample.csv')

# 1) df.head() and df.info() — what does the data look like?
display(cl.head())
cl.info()

# 2) df['column'].value_counts() — what are the most common values?
print("\nRows per dataset slice (miranda vs seattle federal vs king county appellate):")
print(cl['dataset'].value_counts())

# 3) df[df['column'] > value] — filter to a subset (decisions on or after 1990-01-01)
cl['_decision_dt'] = pd.to_datetime(cl['date_of_decision'], errors='coerce')
recent = cl[cl['_decision_dt'] >= pd.Timestamp('1990-01-01')]
print(f"\nFiltered to decisions on or after 1990-01-01: {len(recent)} rows")
display(recent.head())

# 4) df.groupby('column')['other'].mean() — group and summarize mean cite_count by dataset slice
print("\nMean cite_count by dataset:")
print(cl.groupby('dataset')['cite_count'].mean().round(2))

# 5) df.isnull().sum() — find missing data (judge is often sparse in API exports)
print("\nMissing values per column:")
print(cl.isnull().sum())

---
## The Cursor prompt pattern

You do not need to memorize pandas syntax. You need to know what question you're trying to answer, and you need to be able to read the output once you have it.

When you need code you haven't seen before, open the Cursor chat panel and use this pattern:

```
I have a DataFrame called df with columns: id, app, category, rating, review,
date, helpful_votes, verified_purchase, device_type, app_version.

Show me how to [describe the operation in plain English].
```

**Weak prompt:** `how do I use groupby`
**Strong prompt:** `I have a DataFrame with columns app and rating. Show me the average rating per app, sorted from lowest to highest, with the count of reviews for each app.`

The difference: the strong prompt tells Cursor what columns you have and what the output should look like. You get code you can run immediately.

---
## The first-look checklist — summary

```python
df = pd.read_csv('your_file.csv')   # load

df.head()                            # first five rows
df.tail()                            # last five rows
df.info()                            # columns, types, non-null counts
df.describe()                        # numeric summary stats
df.describe(include='all')           # includes categoricals

df.isnull().sum()                    # missing value count per column
df.isnull().mean().mul(100).round(1) # missing as percentage

df['col'].value_counts()             # distribution of a categorical column
df['col'].value_counts(dropna=False) # include NaN in the count

df[df['col'] > value]                # filter rows
df[(df['col1'] > v1) & (df['col2'] == v2)]  # stacked filter

df.groupby('cat_col')['num_col'].mean()      # group and aggregate
df.groupby('cat_col')['num_col'].agg(['mean','count','std'])
```

Run these in order. Every time. On every new dataset.